# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-03 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='anonymous_user_fname', max_length=50)),
                ('lastname', models.CharField(default='anonymous_user_lname', max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('dob', models.DateField(default=datetime.datetime.now)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], default='MALE', max_length=6)),
                ('mobile', models.CharField(default='anonymous_mobile', max_length=14)),
                ('comment', models.CharField(default='anonymous_COMMENT', max_length=540)),
                ('reg_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
